require('../node_modules/convertlab-uilib');
require('../node_modules/convertlab-scaffold');
require('../node_modules/convertlab-ui-common');
require('../node_modules/convertlab-uilib-ana');
require('jquery/dist/jquery.min.js');
require('lodash/lodash.min.js');
require('moment/min/moment.min.js');
require('moment/locale/zh-cn');
require('react/dist/react.min.js');
require('react-dom/dist/react-dom.min.js');
require('react-router/umd/ReactRouter.min.js');
require('redux/dist/redux.min.js');
require('react-redux/dist/react-redux.min.js');
require('antd/dist/antd.min.js');
// require('echarts/dist/echarts.min.js');
// require('jsplumb/dist/js/jsPlumb-2.1.3-min.js');
// require('jquery.easing/jquery.easing.1.3.js');
require('components-jquery-htmlclean/jquery.htmlClean.js');
// require('jspdf/dist/jspdf.debug.js');
// require('codemirror/lib/codemirror.css');
// require('codemirror/theme/monokai.css');
// require('intro.js/minified/intro.min.js');
// require('intro.js/introjs.css');
// require('canvg/canvg.js');
// require('canvg/rgbcolor.js');
// require('canvg/StackBlur.js');
// require('html2canvas/dist/html2canvas.js');
require('react-dates/lib/css/_datepicker.css');
